enum GUI_EVENT{
    MENU_CLICK = 0,
    CLEAR_CLICK,
    CULLING,
    ANTIALIASING,
    Z_BUFFER,
    SHOW_FILL,
    SHOW_VERTICES,
    SHOW_EDGES,
    SHOW_BOUNDING_BOX,
    SHOW_NORMALS,
    IMPORT_OBJ,
    IMPORT_MTL,
    IMPORT_SCENE,
    EXPORT_SCENE,
    PHONG_SHADING
};